--------------------------------------------------------
--  파일이 생성됨 - 화요일-1월-21-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table EXAM
--------------------------------------------------------

  CREATE TABLE "CBT"."EXAM" 
   (	"EXAM_NO" NUMBER(10,0), 
	"EXAM_NM" VARCHAR2(100 BYTE), 
	"QUEST_COUNT" NUMBER(2,0), 
	"EXAM_TIME" NUMBER(3,0), 
	"QUEST_GROUP" VARCHAR2(3 BYTE), 
	"EXAM_DESC" VARCHAR2(4000 BYTE), 
	"EXAM_TYPE" VARCHAR2(3 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "CBT"."EXAM"."EXAM_NO" IS '시험지번호';
   COMMENT ON COLUMN "CBT"."EXAM"."EXAM_NM" IS '시험지명';
   COMMENT ON COLUMN "CBT"."EXAM"."QUEST_COUNT" IS '문항수';
   COMMENT ON COLUMN "CBT"."EXAM"."EXAM_TIME" IS '시험시간';
   COMMENT ON COLUMN "CBT"."EXAM"."QUEST_GROUP" IS '문제유형';
   COMMENT ON COLUMN "CBT"."EXAM"."EXAM_DESC" IS '상세정보';
   COMMENT ON COLUMN "CBT"."EXAM"."EXAM_TYPE" IS '출제유형';
--------------------------------------------------------
--  DDL for Table EXAM_QUEST
--------------------------------------------------------

  CREATE TABLE "CBT"."EXAM_QUEST" 
   (	"EXAM_NO" NUMBER(10,0), 
	"QUEST_NO" NUMBER(10,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "CBT"."EXAM_QUEST"."EXAM_NO" IS '시험지번호';
   COMMENT ON COLUMN "CBT"."EXAM_QUEST"."QUEST_NO" IS '문제번호';
--------------------------------------------------------
--  DDL for Table MEMBER
--------------------------------------------------------

  CREATE TABLE "CBT"."MEMBER" 
   (	"ID" VARCHAR2(20 BYTE), 
	"PW" VARCHAR2(20 BYTE), 
	"NAME" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "CBT"."MEMBER"."ID" IS '아이디';
   COMMENT ON COLUMN "CBT"."MEMBER"."PW" IS '패스워드';
   COMMENT ON COLUMN "CBT"."MEMBER"."NAME" IS '사용자명';
--------------------------------------------------------
--  DDL for Table QUEST
--------------------------------------------------------

  CREATE TABLE "CBT"."QUEST" 
   (	"QUEST_NO" NUMBER(10,0), 
	"QUEST_CONTENT" VARCHAR2(4000 BYTE), 
	"QUEST_TYPE" VARCHAR2(3 BYTE), 
	"ANSWER1" VARCHAR2(1000 BYTE), 
	"ANSWER2" VARCHAR2(1000 BYTE), 
	"ANSWER3" VARCHAR2(1000 BYTE), 
	"ANSWER4" VARCHAR2(1000 BYTE), 
	"RIGHT_ANSWER" CHAR(1 BYTE), 
	"EXPLAIN" VARCHAR2(4000 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "CBT"."QUEST"."QUEST_NO" IS '문제번호';
   COMMENT ON COLUMN "CBT"."QUEST"."QUEST_CONTENT" IS '문제';
   COMMENT ON COLUMN "CBT"."QUEST"."QUEST_TYPE" IS '문제유형';
   COMMENT ON COLUMN "CBT"."QUEST"."ANSWER1" IS '답1';
   COMMENT ON COLUMN "CBT"."QUEST"."ANSWER2" IS '답2';
   COMMENT ON COLUMN "CBT"."QUEST"."ANSWER3" IS '답3';
   COMMENT ON COLUMN "CBT"."QUEST"."ANSWER4" IS '답4';
   COMMENT ON COLUMN "CBT"."QUEST"."RIGHT_ANSWER" IS '정답';
   COMMENT ON COLUMN "CBT"."QUEST"."EXPLAIN" IS '해설';
--------------------------------------------------------
--  DDL for Table TAKE_QUEST
--------------------------------------------------------

  CREATE TABLE "CBT"."TAKE_QUEST" 
   (	"TR_NO" NUMBER(10,0), 
	"QUEST_NO" NUMBER(10,0), 
	"QUEST_ORD" NUMBER(1,0), 
	"ANSWER" VARCHAR2(1 BYTE), 
	"RIGHT_YN" CHAR(1 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "CBT"."TAKE_QUEST"."TR_NO" IS '응시결과번호';
   COMMENT ON COLUMN "CBT"."TAKE_QUEST"."QUEST_NO" IS '문제번호';
   COMMENT ON COLUMN "CBT"."TAKE_QUEST"."QUEST_ORD" IS '문제순서';
   COMMENT ON COLUMN "CBT"."TAKE_QUEST"."ANSWER" IS '답안';
   COMMENT ON COLUMN "CBT"."TAKE_QUEST"."RIGHT_YN" IS '정답여부';
--------------------------------------------------------
--  DDL for Table TAKE_RESULT
--------------------------------------------------------

  CREATE TABLE "CBT"."TAKE_RESULT" 
   (	"TR_NO" NUMBER(10,0), 
	"EXAM_NO" NUMBER(10,0), 
	"ID" VARCHAR2(20 BYTE), 
	"TR_DT" DATE, 
	"SCORE" NUMBER(10,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "CBT"."TAKE_RESULT"."TR_NO" IS '응시결과번호';
   COMMENT ON COLUMN "CBT"."TAKE_RESULT"."EXAM_NO" IS '시험지번호';
   COMMENT ON COLUMN "CBT"."TAKE_RESULT"."ID" IS '아이디';
   COMMENT ON COLUMN "CBT"."TAKE_RESULT"."TR_DT" IS '응시일시';
   COMMENT ON COLUMN "CBT"."TAKE_RESULT"."SCORE" IS '점수';
REM INSERTING into CBT.EXAM
SET DEFINE OFF;
Insert into CBT.EXAM (EXAM_NO,EXAM_NM,QUEST_COUNT,EXAM_TIME,QUEST_GROUP,EXAM_DESC,EXAM_TYPE) values (3,'freefree',10,2,'002','dao test입니다','R');
Insert into CBT.EXAM (EXAM_NO,EXAM_NM,QUEST_COUNT,EXAM_TIME,QUEST_GROUP,EXAM_DESC,EXAM_TYPE) values (1,'first',3,2,'003','detail','A');
Insert into CBT.EXAM (EXAM_NO,EXAM_NM,QUEST_COUNT,EXAM_TIME,QUEST_GROUP,EXAM_DESC,EXAM_TYPE) values (2,'EXAM_NM',1,1,'001','EXAM_DESC','R');
REM INSERTING into CBT.EXAM_QUEST
SET DEFINE OFF;
REM INSERTING into CBT.MEMBER
SET DEFINE OFF;
REM INSERTING into CBT.QUEST
SET DEFINE OFF;
Insert into CBT.QUEST (QUEST_NO,QUEST_CONTENT,QUEST_TYPE,ANSWER1,ANSWER2,ANSWER3,ANSWER4,RIGHT_ANSWER,EXPLAIN) values (1,'수정된 문제','001','수정답1','수정답2','수정답3','수정답4','3','수정해설');
REM INSERTING into CBT.TAKE_QUEST
SET DEFINE OFF;
REM INSERTING into CBT.TAKE_RESULT
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index EXAM_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "CBT"."EXAM_PK" ON "CBT"."EXAM" ("EXAM_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index TAKE_QUEST_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "CBT"."TAKE_QUEST_PK" ON "CBT"."TAKE_QUEST" ("TR_NO", "QUEST_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index QUEST_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "CBT"."QUEST_PK" ON "CBT"."QUEST" ("QUEST_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index TAKE_RESULT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "CBT"."TAKE_RESULT_PK" ON "CBT"."TAKE_RESULT" ("TR_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index EXAM_QUEST_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "CBT"."EXAM_QUEST_PK" ON "CBT"."EXAM_QUEST" ("EXAM_NO", "QUEST_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index MEMBER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "CBT"."MEMBER_PK" ON "CBT"."MEMBER" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table MEMBER
--------------------------------------------------------

  ALTER TABLE "CBT"."MEMBER" ADD CONSTRAINT "MEMBER_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "CBT"."MEMBER" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table QUEST
--------------------------------------------------------

  ALTER TABLE "CBT"."QUEST" ADD CONSTRAINT "QUEST_PK" PRIMARY KEY ("QUEST_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "CBT"."QUEST" MODIFY ("QUEST_NO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table EXAM_QUEST
--------------------------------------------------------

  ALTER TABLE "CBT"."EXAM_QUEST" ADD CONSTRAINT "EXAM_QUEST_PK" PRIMARY KEY ("EXAM_NO", "QUEST_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "CBT"."EXAM_QUEST" MODIFY ("QUEST_NO" NOT NULL ENABLE);
  ALTER TABLE "CBT"."EXAM_QUEST" MODIFY ("EXAM_NO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TAKE_QUEST
--------------------------------------------------------

  ALTER TABLE "CBT"."TAKE_QUEST" ADD CONSTRAINT "TAKE_QUEST_PK" PRIMARY KEY ("TR_NO", "QUEST_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "CBT"."TAKE_QUEST" MODIFY ("QUEST_NO" NOT NULL ENABLE);
  ALTER TABLE "CBT"."TAKE_QUEST" MODIFY ("TR_NO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table EXAM
--------------------------------------------------------

  ALTER TABLE "CBT"."EXAM" ADD CONSTRAINT "EXAM_PK" PRIMARY KEY ("EXAM_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "CBT"."EXAM" MODIFY ("EXAM_NO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TAKE_RESULT
--------------------------------------------------------

  ALTER TABLE "CBT"."TAKE_RESULT" ADD CONSTRAINT "TAKE_RESULT_PK" PRIMARY KEY ("TR_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "CBT"."TAKE_RESULT" MODIFY ("TR_NO" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table EXAM_QUEST
--------------------------------------------------------

  ALTER TABLE "CBT"."EXAM_QUEST" ADD CONSTRAINT "EXAM_QUEST_FK1" FOREIGN KEY ("EXAM_NO")
	  REFERENCES "CBT"."EXAM" ("EXAM_NO") ENABLE;
  ALTER TABLE "CBT"."EXAM_QUEST" ADD CONSTRAINT "EXAM_QUEST_FK2" FOREIGN KEY ("QUEST_NO")
	  REFERENCES "CBT"."QUEST" ("QUEST_NO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TAKE_QUEST
--------------------------------------------------------

  ALTER TABLE "CBT"."TAKE_QUEST" ADD CONSTRAINT "TAKE_QUEST_FK1" FOREIGN KEY ("TR_NO")
	  REFERENCES "CBT"."TAKE_RESULT" ("TR_NO") ENABLE;
  ALTER TABLE "CBT"."TAKE_QUEST" ADD CONSTRAINT "TAKE_QUEST_FK2" FOREIGN KEY ("QUEST_NO")
	  REFERENCES "CBT"."QUEST" ("QUEST_NO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TAKE_RESULT
--------------------------------------------------------

  ALTER TABLE "CBT"."TAKE_RESULT" ADD CONSTRAINT "TAKE_RESULT_FK1" FOREIGN KEY ("EXAM_NO")
	  REFERENCES "CBT"."EXAM" ("EXAM_NO") ENABLE;
  ALTER TABLE "CBT"."TAKE_RESULT" ADD CONSTRAINT "TAKE_RESULT_FK2" FOREIGN KEY ("ID")
	  REFERENCES "CBT"."MEMBER" ("ID") ENABLE;
